micronaut:
  application:
    name: app
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  prometheus:
    sensitive: false

datasources:
  default:
    url: jdbc:postgresql://postgres_attendance:5432/attendance
    username: postgres
    password: 'admin'
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
