micronaut:
  application:
    name: app

datasources:
  default:
    url: jdbc:postgresql://postgres_attendance:5432/attendance
    username: postgres
    password: 'admin'
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
