name: Build and Publish Docker JVM Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - run: |
          echo "JAVA_HOME: $JAVA_HOME"
          java --version

      - name: Build Micronaut project
        run: |
          ./mvnw package -Dpackaging=docker
          docker images -a
          docker tag app:latest joaocipriano/micronaut-jvm:latest
        shell: bash

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish Micronaut Docker image to DockerHub
        run: |
          docker push joaocipriano/micronaut-jvm:latest
        shell: bash